/**
 * SL departure board bitmap font.
 *
 * Core glyphs traced from zmullett/Stockholm-SL-sign-font
 * (https://github.com/zmullett/Stockholm-SL-sign-font), which digitised the
 * dot-matrix characters used on Stockholm T-bana departure signs.
 *
 * Missing characters (digits 2, 9; most uppercase and several lowercase
 * letters; Swedish Ä/Ö; punctuation) were designed to match the proportional,
 * 2-pixel-stroke style of the originals.
 *
 * Each glyph is an array of row strings.
 *   'x' = lit pixel   ' ' = dark pixel
 * All rows within a glyph have the same length (= the glyph width).
 * The normal character body is CELL_HEIGHT (10) rows tall.
 * Glyphs with descenders (g, j, p, q, y, comma, semicolon) have 12 rows;
 * the two extra rows sit below the baseline.
 */

/** Height of the standard character body (rows 0–9). */
export const CELL_HEIGHT = 10;

/** Extra rows below the baseline used by descender characters. */
export const DESCENDER_HEIGHT = 2;

export interface Glyph {
  readonly rows: readonly string[];
  /** Width in pixels (= length of any row string). */
  readonly width: number;
}

export interface BitmapFont {
  readonly cellHeight: number;
  readonly getGlyph: (char: string) => Glyph | undefined;
}

// ---------------------------------------------------------------------------
// Raw glyph data
// Each entry: character → array of row strings (all the same length).
// ---------------------------------------------------------------------------

const RAW: Record<string, readonly string[]> = {
  // ── Space ──────────────────────────────────────────────────────────────
  ' ': [
    '   ',
    '   ',
    '   ',
    '   ',
    '   ',
    '   ',
    '   ',
    '   ',
    '   ',
    '   ',
  ],

  // ── Digits ─────────────────────────────────────────────────────────────
  '0': [
    '  xx  ',
    ' x  x ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' x  x ',
    '  xx  ',
  ],
  '1': [
    '  xx',
    ' xxx',
    'xxxx',
    '  xx',
    '  xx',
    '  xx',
    '  xx',
    '  xx',
    '  xx',
    '  xx',
  ],
  '2': [
    ' xxxx ',
    'xx  xx',
    '    xx',
    '    xx',
    '   xx ',
    '  xx  ',
    ' xx   ',
    'xx    ',
    'xx  xx',
    'xxxxxx',
  ],
  '3': [
    ' xxxx ',
    'xx  xx',
    '    xx',
    '    xx',
    '  xxx ',
    '    xx',
    '    xx',
    '    xx',
    'xx  xx',
    ' xxxx ',
  ],
  '4': [
    '    xx',
    '   xxx',
    '  xxxx',
    ' xx xx',
    'xx  xx',
    'xx  xx',
    'xxxxxx',
    '    xx',
    '    xx',
    '    xx',
  ],
  '5': [
    'xxxxxx',
    'xx    ',
    'xx    ',
    'xx    ',
    'xxxxx ',
    '    xx',
    '    xx',
    '    xx',
    'xx  xx',
    ' xxxx ',
  ],
  '6': [
    ' xxxx ',
    'xx  xx',
    'xx    ',
    'xx    ',
    'xxxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxx ',
  ],
  '7': [
    'xxxxxx',
    '    xx',
    '    xx',
    '   xx ',
    '   xx ',
    '  xx  ',
    '  xx  ',
    '  xx  ',
    '  xx  ',
    '  xx  ',
  ],
  '8': [
    ' xxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxx ',
  ],
  '9': [
    ' xxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxxx',
    '    xx',
    '    xx',
    '    xx',
    'xx  xx',
    ' xxxx ',
  ],

  // ── Uppercase letters ──────────────────────────────────────────────────
  'A': [
    '  xx  ',
    ' x  x ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xxxxxx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
  ],
  'B': [
    'xxxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xxxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xxxxx ',
  ],
  'C': [
    ' xxxx ',
    'xxxxxx',
    'xx  xx',
    'xx    ',
    'xx    ',
    'xx    ',
    'xx    ',
    'xx  xx',
    'xxxxxx',
    ' xxxx ',
  ],
  'D': [
    'xxxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xxxxx ',
  ],
  'E': [
    'xxxxxx',
    'xx    ',
    'xx    ',
    'xx    ',
    'xxxxx ',
    'xx    ',
    'xx    ',
    'xx    ',
    'xx    ',
    'xxxxxx',
  ],
  'F': [
    'xxxxxx',
    'xx    ',
    'xx    ',
    'xx    ',
    'xxxxx ',
    'xx    ',
    'xx    ',
    'xx    ',
    'xx    ',
    'xx    ',
  ],
  'G': [
    ' xxxx ',
    'xxxxxx',
    'xx    ',
    'xx    ',
    'xx    ',
    'xx xxx',
    'xx  xx',
    'xx  xx',
    'xxxxxx',
    ' xxxx ',
  ],
  'H': [
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xxxxxx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
  ],
  'I': [
    'xxxx',
    ' xx ',
    ' xx ',
    ' xx ',
    ' xx ',
    ' xx ',
    ' xx ',
    ' xx ',
    ' xx ',
    'xxxx',
  ],
  'J': [
    '  xxxx',
    '    xx',
    '    xx',
    '    xx',
    '    xx',
    '    xx',
    '    xx',
    '    xx',
    'xx  xx',
    ' xxxx ',
  ],
  'K': [
    'xx   xx',
    'xx  xx ',
    'xx xx  ',
    'xxxx   ',
    'xxx    ',
    'xxx    ',
    'xxxx   ',
    'xx xx  ',
    'xx  xx ',
    'xx   xx',
  ],
  'L': [
    'xx    ',
    'xx    ',
    'xx    ',
    'xx    ',
    'xx    ',
    'xx    ',
    'xx    ',
    'xx    ',
    'xx    ',
    'xxxxxx',
  ],
  'M': [
    'x     x',
    'xx   xx',
    'xxx xxx',
    'xxxxxxx',
    'xxxxxxx',
    'xx x xx',
    'xx   xx',
    'xx   xx',
    'xx   xx',
    'xx   xx',
  ],
  'N': [
    'xx   xx',
    'xxx  xx',
    'xxxx xx',
    'xxxxxxx',
    'xx xxxx',
    'xx  xxx',
    'xx   xx',
    'xx   xx',
    'xx   xx',
    'xx   xx',
  ],
  'O': [
    ' xxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxx ',
  ],
  'P': [
    'xxxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xxxxx ',
    'xx    ',
    'xx    ',
    'xx    ',
    'xx    ',
  ],
  'Q': [
    ' xxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx xxx',
    ' xxxxx',
    '    xx',
  ],
  'R': [
    'xxxxx ',
    'xxxxxx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xxxxxx',
    'xxxxx ',
    'xx xx ',
    'xx  xx',
    'xx  xx',
  ],
  'S': [
    ' xxxx ',
    'xx  xx',
    'xx    ',
    'xx    ',
    ' xxxx ',
    '    xx',
    '    xx',
    '    xx',
    'xx  xx',
    ' xxxx ',
  ],
  'T': [
    'xxxxxx',
    '  xx  ',
    '  xx  ',
    '  xx  ',
    '  xx  ',
    '  xx  ',
    '  xx  ',
    '  xx  ',
    '  xx  ',
    '  xx  ',
  ],
  'U': [
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxx ',
  ],
  'V': [
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxx ',
    ' xxxx ',
    '  xx  ',
    '  xx  ',
  ],
  'W': [
    'xx   xx',
    'xx   xx',
    'xx   xx',
    'xx   xx',
    'xx x xx',
    'xx x xx',
    'xxxxxxx',
    'xxxxxxx',
    'xxx xxx',
    'xx   xx',
  ],
  'X': [
    'xx  xx',
    'xx  xx',
    ' xxxx ',
    '  xx  ',
    '  xx  ',
    '  xx  ',
    ' xxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
  ],
  'Y': [
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxx ',
    '  xx  ',
    '  xx  ',
    '  xx  ',
    '  xx  ',
    '  xx  ',
  ],
  'Z': [
    'xxxxxx',
    '    xx',
    '    xx',
    '   xx ',
    '  xx  ',
    '  xx  ',
    ' xx   ',
    'xx    ',
    'xx    ',
    'xxxxxx',
  ],

  // ── Swedish uppercase ──────────────────────────────────────────────────
  'Å': [
    '  xx  ',
    ' x  x ',
    '  xx  ',
    ' x  x ',
    'xx  xx',
    'xx  xx',
    'xxxxxx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
  ],
  'Ä': [
    'xx  xx',
    '      ',
    '  xx  ',
    ' x  x ',
    'xx  xx',
    'xx  xx',
    'xxxxxx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
  ],
  'Ö': [
    'xx  xx',
    '      ',
    ' xxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxx ',
  ],

  // ── Lowercase letters ──────────────────────────────────────────────────
  'a': [
    '      ',
    '      ',
    ' xxxx ',
    'xx  xx',
    '    xx',
    ' xxxxx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxxx',
  ],
  'b': [
    'xx    ',
    'xx    ',
    'xxxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xxxxx ',
  ],
  'c': [
    '      ',
    '      ',
    ' xxxx ',
    'xx  xx',
    'xx    ',
    'xx    ',
    'xx    ',
    'xx    ',
    'xx  xx',
    ' xxxx ',
  ],
  'd': [
    '    xx',
    '    xx',
    ' xxxxx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxxx',
  ],
  'e': [
    '      ',
    '      ',
    ' xxxx ',
    'xx  xx',
    'xx  xx',
    'xxxxxx',
    'xx    ',
    'xx    ',
    'xx  xx',
    ' xxxx ',
  ],
  'f': [
    '  xx',
    ' xx ',
    ' xx ',
    'xxxx',
    ' xx ',
    ' xx ',
    ' xx ',
    ' xx ',
    ' xx ',
    ' xx ',
  ],
  // 12 rows — rows 10–11 are the descender below the baseline
  'g': [
    '      ',
    '      ',
    ' xxxxx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxxx',
    '    xx',
    'xx  xx',
    ' xxxx ',
  ],
  'h': [
    'xx    ',
    'xx    ',
    'xxxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
  ],
  'i': [
    'xx',
    '  ',
    'xx',
    'xx',
    'xx',
    'xx',
    'xx',
    'xx',
    'xx',
    'xx',
  ],
  // 12 rows — rows 10–11 are the descender
  'j': [
    '  x',
    '   ',
    '  x',
    '  x',
    '  x',
    '  x',
    '  x',
    '  x',
    '  x',
    '  x',
    ' xx',
    'xx ',
  ],
  'k': [
    'xx    ',
    'xx    ',
    'xx  xx',
    'xx xx ',
    'xxxx  ',
    'xxx   ',
    'xxx   ',
    'xxxx  ',
    'xx xx ',
    'xx  xx',
  ],
  'l': [
    'xx',
    'xx',
    'xx',
    'xx',
    'xx',
    'xx',
    'xx',
    'xx',
    'xx',
    'xx',
  ],
  'm': [
    '        ',
    '        ',
    'xxxxxxx ',
    'xx xx xx',
    'xx xx xx',
    'xx xx xx',
    'xx xx xx',
    'xx xx xx',
    'xx xx xx',
    'xx xx xx',
  ],
  'n': [
    '     ',
    '     ',
    'xxxx ',
    'xx xx',
    'xx xx',
    'xx xx',
    'xx xx',
    'xx xx',
    'xx xx',
    'xx xx',
  ],
  'o': [
    '      ',
    '      ',
    ' xxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxx ',
  ],
  // 12 rows — rows 10–11 are the descender
  'p': [
    '      ',
    '      ',
    'xxxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xxxxx ',
    'xx    ',
    'xx    ',
  ],
  // 12 rows — rows 10–11 are the descender
  'q': [
    '      ',
    '      ',
    ' xxxxx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxxx',
    '    xx',
    '    xx',
    '    xx',
  ],
  'r': [
    '     ',
    '     ',
    'xx xx',
    'xxxxx',
    'xxx  ',
    'xx   ',
    'xx   ',
    'xx   ',
    'xx   ',
    'xx   ',
  ],
  's': [
    '      ',
    '      ',
    ' xxxx ',
    'xx  xx',
    'xx    ',
    ' xxxx ',
    '   xxx',
    '    xx',
    'xx  xx',
    ' xxxx ',
  ],
  't': [
    ' xx ',
    ' xx ',
    'xxxx',
    ' xx ',
    ' xx ',
    ' xx ',
    ' xx ',
    ' xx ',
    ' xx ',
    '  xx',
  ],
  'u': [
    '      ',
    '      ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxx ',
  ],
  'v': [
    '      ',
    '      ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxx ',
    '  xx  ',
  ],
  'w': [
    '       ',
    '       ',
    'xx   xx',
    'xx   xx',
    'xx   xx',
    'xx x xx',
    'xx x xx',
    'xxxxxxx',
    'xxx xxx',
    'xx   xx',
  ],
  'x': [
    '     ',
    '     ',
    'xx xx',
    'xx xx',
    ' xxx ',
    '  x  ',
    ' xxx ',
    'xx xx',
    'xx xx',
    'xx xx',
  ],
  // 12 rows — rows 10–11 are the descender
  'y': [
    '      ',
    '      ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxxx',
    '    xx',
    '    xx',
    'xx  xx',
    ' xxxx ',
  ],
  'z': [
    '     ',
    '     ',
    'xxxxx',
    '   xx',
    '  xx ',
    '  xx ',
    ' xx  ',
    'xx   ',
    'xx   ',
    'xxxxx',
  ],

  // ── Swedish lowercase ──────────────────────────────────────────────────
  'å': [
    '  xx  ',
    ' x  x ',
    '  xx  ',
    ' xxxx ',
    'xx  xx',
    '    xx',
    ' xxxxx',
    'xx  xx',
    'xx  xx',
    ' xxxxx',
  ],
  'ä': [
    'xx  xx',
    '      ',
    ' xxxx ',
    'xx  xx',
    '    xx',
    ' xxxxx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxxx',
  ],
  'ö': [
    'xx  xx',
    '      ',
    ' xxxx ',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    'xx  xx',
    ' xxxx ',
  ],

  // ── Punctuation & symbols ──────────────────────────────────────────────
  '!': [
    'xx',
    'xx',
    'xx',
    'xx',
    'xx',
    'xx',
    'xx',
    '  ',
    'xx',
    'xx',
  ],
  '"': [
    'x x ',
    'x x ',
    'x x ',
    '    ',
    '    ',
    '    ',
    '    ',
    '    ',
    '    ',
    '    ',
  ],
  // 12 rows — row 10–11 are the descender tail of the comma
  ',': [
    '  ',
    '  ',
    '  ',
    '  ',
    '  ',
    '  ',
    '  ',
    '  ',
    'xx',
    'xx',
    ' x',
    'x ',
  ],
  '-': [
    '    ',
    '    ',
    '    ',
    '    ',
    '    ',
    'xxxx',
    '    ',
    '    ',
    '    ',
    '    ',
  ],
  '.': [
    '  ',
    '  ',
    '  ',
    '  ',
    '  ',
    '  ',
    '  ',
    '  ',
    'xx',
    'xx',
  ],
  '/': [
    '   x',
    '   x',
    '  xx',
    '  xx',
    ' xx ',
    ' xx ',
    'xx  ',
    'xx  ',
    'x   ',
    'x   ',
  ],
  ':': [
    '  ',
    '  ',
    '  ',
    'xx',
    'xx',
    '  ',
    '  ',
    'xx',
    'xx',
    '  ',
  ],
  // 12 rows — the tail of the semicolon is a descender
  ';': [
    '  ',
    '  ',
    '  ',
    'xx',
    'xx',
    '  ',
    '  ',
    'xx',
    'xx',
    ' x',
    'x ',
    '  ',
  ],
  '?': [
    ' xxxx ',
    'xx  xx',
    '    xx',
    '    xx',
    '   xx ',
    '  xx  ',
    '  xx  ',
    '      ',
    '  xx  ',
    '  xx  ',
  ],
  '(': [
    '  xx',
    ' xx ',
    'xx  ',
    'xx  ',
    'xx  ',
    'xx  ',
    'xx  ',
    'xx  ',
    ' xx ',
    '  xx',
  ],
  ')': [
    'xx  ',
    ' xx ',
    '  xx',
    '  xx',
    '  xx',
    '  xx',
    '  xx',
    '  xx',
    ' xx ',
    'xx  ',
  ],
  '*': [
    '      ',
    '      ',
    '  xx  ',
    'x xx x',
    'xxxxxx',
    ' xxxx ',
    'xxxxxx',
    'x xx x',
    '  xx  ',
    '      ',
  ],
  '+': [
    '     ',
    '     ',
    '  x  ',
    '  x  ',
    'xxxxx',
    '  x  ',
    '  x  ',
    '     ',
    '     ',
    '     ',
  ],
  '=': [
    '     ',
    '     ',
    '     ',
    'xxxxx',
    '     ',
    '     ',
    'xxxxx',
    '     ',
    '     ',
    '     ',
  ],
  '_': [
    '      ',
    '      ',
    '      ',
    '      ',
    '      ',
    '      ',
    '      ',
    '      ',
    '      ',
    'xxxxxx',
  ],
  "'": [
    'xx',
    'xx',
    ' x',
    'x ',
    '  ',
    '  ',
    '  ',
    '  ',
    '  ',
    '  ',
  ],
  '#': [
    ' x x ',
    ' x x ',
    'xxxxx',
    ' x x ',
    'xxxxx',
    ' x x ',
    ' x x ',
    '     ',
    '     ',
    '     ',
  ],
  '%': [
    'xx   ',
    'xx  x',
    '   x ',
    '  x  ',
    ' x   ',
    'x  xx',
    '   xx',
    '     ',
    '     ',
    '     ',
  ],
  '&': [
    ' xxx  ',
    'xx  xx',
    'xx  xx',
    ' xxx  ',
    'xxxx  ',
    'xx  xx',
    'xx  xx',
    'xx xxx',
    'xx  xx',
    ' xxx x',
  ],
  '@': [
    ' xxxx ',
    'xx  xx',
    'xx  xx',
    'xx xxx',
    'xxxxxx',
    'xx    ',
    'xx    ',
    'xx  xx',
    'xxxxxx',
    ' xxxx ',
  ],
  '<': [
    '   xx',
    '  xx ',
    ' xx  ',
    'xx   ',
    'xx   ',
    ' xx  ',
    '  xx ',
    '   xx',
    '     ',
    '     ',
  ],
  '>': [
    'xx   ',
    ' xx  ',
    '  xx ',
    '   xx',
    '   xx',
    '  xx ',
    ' xx  ',
    'xx   ',
    '     ',
    '     ',
  ],
  '\\': [
    'x   ',
    'x   ',
    'xx  ',
    'xx  ',
    ' xx ',
    ' xx ',
    '  xx',
    '  xx',
    '   x',
    '   x',
  ],
  '[': [
    'xxx',
    'xx ',
    'xx ',
    'xx ',
    'xx ',
    'xx ',
    'xx ',
    'xx ',
    'xx ',
    'xxx',
  ],
  ']': [
    'xxx',
    ' xx',
    ' xx',
    ' xx',
    ' xx',
    ' xx',
    ' xx',
    ' xx',
    ' xx',
    'xxx',
  ],
};

// ---------------------------------------------------------------------------
// Validate and export
// ---------------------------------------------------------------------------

function buildGlyph(rows: readonly string[]): Glyph {
  const width = Math.max(...rows.map((r) => r.length));
  // Pad every row to the same width so callers don't need to range-check.
  const padded = rows.map((r) => r.padEnd(width, ' '));
  return { rows: padded, width };
}

export const GLYPHS: Readonly<Record<string, Glyph>> = Object.fromEntries(
  Object.entries(RAW).map(([ch, rows]) => [ch, buildGlyph(rows)]),
);

/** Look up a glyph by character. Returns undefined for unknown characters. */
export function getGlyph(char: string): Glyph | undefined {
  return GLYPHS[char];
}

export const SL_FONT: BitmapFont = {
  cellHeight: CELL_HEIGHT,
  getGlyph,
};
