#!/usr/bin/env python3
"""Generate public/python/sl_font.py from src/font/sl-font.ts.

Manual workflow:
  1. Edit glyphs in src/font/sl-font.ts (single source of truth).
  2. Run: python3 scripts/generate-sl-font.py
  3. Confirm: git diff --stat public/python/sl_font.py
  4. Check: python3 -m py_compile public/python/sl_font.py && npm run font:parity
  5. Commit src/font/sl-font.ts and public/python/sl_font.py together.

Nothing invokes this automatically — no CI, build, or test hooks.
"""

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SRC = REPO_ROOT / "src" / "font" / "sl-font.ts"
DEFAULT_OUT = REPO_ROOT / "public" / "python" / "sl_font.py"

ENTRY_RE = re.compile(
    r'''(?m)^\s*'(?P<char>(?:[^'\\]|\\.)*)'\s*:\s*\[\s*$|^  "(?P<dchar>.)":\s*\[\s*$'''
)
ROW_RE = re.compile(r"(?m)^\s*'(?P<row>(?:[^'\\]|\\.)*)'\s*,?\s*$")

HEADER = '''"""SL departure board bitmap font (packed).

DO NOT EDIT — generated by scripts/generate-sl-font.py from src/font/sl-font.ts.
To change a glyph, edit src/font/sl-font.ts then run:
  python3 scripts/generate-sl-font.py

Encoding: GLYPHS maps character -> bytes. Byte 0 is the advance width
(2-8 logical pixels). Bytes 1..N are bitmap rows, one byte per row with
the MSB as the leftmost pixel. 10-row glyphs are 11 bytes; descenders
(g j p q y , ;) are 13 bytes.
"""

CELL_HEIGHT = 10
DESCENDER_HEIGHT = 2
GAP = 1
UNKNOWN_ADVANCE = 3
GLYPH_COUNT = {count}

GLYPHS = {{
{entries}
}}


def get_glyph(ch):
    return GLYPHS.get(ch)


def glyph_width(glyph):
    return glyph[0]
'''


def unescape_ts_string(value):
    out = []
    i = 0
    while i < len(value):
        c = value[i]
        if c == "\\" and i + 1 < len(value):
            nxt = value[i + 1]
            mapping = {"n": "\n", "t": "\t", "r": "\r", "0": "\0"}
            out.append(mapping.get(nxt, nxt))
            i += 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


def escape_py_char(char):
    if char == "'":
        return "\\'"
    if char == "\\":
        return "\\\\"
    if char == "\n":
        return "\\n"
    if char == "\t":
        return "\\t"
    code = ord(char)
    if 32 <= code < 127:
        return char
    return "\\u{:04x}".format(code)


def parse_ts_raw(text):
    raw_start = text.index("const RAW")
    raw_end = text.index("};", raw_start)
    block = text[raw_start:raw_end]
    glyphs = {}
    headers = list(ENTRY_RE.finditer(block))
    for index, match in enumerate(headers):
        raw_char = match.group("char")
        if raw_char is None:
            char = match.group("dchar")
        else:
            char = unescape_ts_string(raw_char)
        body_start = match.end()
        body_end = (
            headers[index + 1].start() if index + 1 < len(headers) else len(block)
        )
        body = block[body_start:body_end]
        rows = [
            unescape_ts_string(m.group("row")) for m in ROW_RE.finditer(body)
        ]
        glyphs[char] = rows
    return glyphs


def validate_glyphs(glyphs):
    errors = []
    for char, rows in glyphs.items():
        if len(rows) not in (10, 12):
            errors.append(
                "{!r}: expected 10 or 12 rows, got {}".format(char, len(rows))
            )
            continue
        widths = {len(row) for row in rows}
        if len(widths) != 1:
            errors.append("{!r}: ragged rows {}".format(char, sorted(widths)))
            continue
        width = widths.pop()
        if not 2 <= width <= 8:
            errors.append(
                "{!r}: width {} outside 2-8".format(char, width)
            )
        for row in rows:
            for cell in row:
                if cell not in ("x", " "):
                    errors.append(
                        "{!r}: illegal cell {!r}".format(char, cell)
                    )
                    break
    if errors:
        raise ValueError("invalid glyphs:\n" + "\n".join(errors))


def pack_glyph(rows):
    width = len(rows[0])
    packed = bytearray()
    packed.append(width)
    for row in rows:
        byte = 0
        for dx, cell in enumerate(row):
            if cell == "x":
                byte |= 0x80 >> dx
        packed.append(byte)
    return bytes(packed)


def format_bytes(packed):
    return 'b"' + "".join("\\x{:02x}".format(b) for b in packed) + '"'


def render_output(glyphs):
    lines = []
    for char in sorted(glyphs):
        rows = glyphs[char]
        lines.append(
            "    '{}': {},".format(escape_py_char(char), format_bytes(pack_glyph(rows)))
        )
    return HEADER.format(count=len(glyphs), entries="\n".join(lines))


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate public/python/sl_font.py from src/font/sl-font.ts."
    )
    parser.add_argument(
        "--src", default=str(DEFAULT_SRC), help="Path to sl-font.ts"
    )
    parser.add_argument(
        "--out", default=str(DEFAULT_OUT), help="Path to write sl_font.py"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare against the checked-in file without writing; exit non-zero on drift.",
    )
    args = parser.parse_args(argv)

    src_path = Path(args.src)
    out_path = Path(args.out)
    glyphs = parse_ts_raw(src_path.read_text(encoding="utf-8"))
    if not glyphs:
        raise SystemExit("no glyphs parsed from {}".format(src_path))
    validate_glyphs(glyphs)
    output = render_output(glyphs)

    if args.check:
        current = (
            out_path.read_text(encoding="utf-8") if out_path.exists() else ""
        )
        if current != output:
            print(
                "sl_font.py is stale: run python3 scripts/generate-sl-font.py",
                file=sys.stderr,
            )
            return 1
        print("sl_font.py matches src/font/sl-font.ts ({} glyphs)".format(len(glyphs)))
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(output, encoding="utf-8")
    print("wrote {} ({} glyphs)".format(out_path, len(glyphs)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
