/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeviceDiagnostics: typeof import('./components/device-diagnostics.vue')['default']
    DeviceDisplayPicker: typeof import('./components/device-display-picker.vue')['default']
    DiagnosticFields: typeof import('./components/diagnostic-fields.vue')['default']
    DisplayBoard: typeof import('./components/display-board.vue')['default']
    FilterPicker: typeof import('./components/filter-picker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StopPicker: typeof import('./components/stop-picker.vue')['default']
    UApp: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UFormField: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputMenu: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue')['default']
    USelect: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
  }
}
